on:
  pull_request:
    types:
      - 'opened'
      - 'reopened'
jobs:
  execute-scan-workflow:
    uses: threatrix/threat-agent-scan/.github/workflows/scan-repo-reusable.yaml@master
    with:
      eid: 66439b07-67ca-4c50-b4c3-e5bc6ca9398f
      oid: 652051f0-a30b-4595-9c13-46fdd7bc9d12
      app-name: vue-20220125_alice14
      trx-host: https://stage.threatrix.io
    secrets:
      TOKEN: ${{ secrets.GITHUB_TOKEN }}
      THREATRIX_SERVER_API_KEY: ${{ secrets.THREATRIX_API_KEY }}
